dump_stack: convert generic dump_stack into a weak symbol
We want to move dump_stack related functions out of printk C
code and consolidate them in lib/dump_stack file. The reason why
dump_stack_print_info()/etc ended up in printk.c was a "generic"
(dummy) lib dump_stack() function, which archs can override.
For example, blackfin and nds32, define their own EXPORT_SYMBOL
dump_stack() functions.

In case of blackfin that arch-specific dump_stack() symbol invokes
a global dump_stack_print_info() function. So we can't easily move
dump_stack_print_info() to lib/dump_stack, because this way we will
link with lib/dump_stack.o file, which will bring in a generic
dump_stack() symbol with it, causing a multiple definitions error:
  - one dump_stack() from arch/blackfin/dumpstack
  - the other one from lib/dump_stack

Convert generic dump_stack() into a weak symbol. So we will be
able link with lib/dump_stack and at the same time archs will
be able to override dump_stack(). It also opens up a way for us
to move dump_stack_set_arch_desc(), dump_stack_print_info() and
show_regs_print_info() to lib/dump_stack.

Link: http://lkml.kernel.org/r/20180305053742.9149-1-sergey.senozhatsky@gmail.com
To: Tejun Heo <tj@kernel.org>
To: Steven Rostedt <rostedt@goodmis.org>
To: Dave Young <dyoung@redhat.com>
To: Andi Kleen <ak@linux.intel.com>
To: Greentime Hu <green.hu@gmail.com>
To: Vincent Chen <deanbo422@gmail.com>
To: Arnd Bergmann <arnd@arndb.de>
Cc: Peter Zijlstra <peterz@infradead.org>
Cc: Andrew Morton <akpm@linux-foundation.org>
Cc: Stephen Rothwell <sfr@canb.auug.org.au>
Cc: adi-buildroot-devel@lists.sourceforge.net
Cc: linux-kernel@vger.kernel.org
Signed-off-by: Sergey Senozhatsky <sergey.senozhatsky@gmail.com>
Acked-by: Greentime Hu <green.hu@gmail.com> # nds32
Signed-off-by: Petr Mladek <pmladek@suse.com>